# ===== Frame settings =====
odom_frame_id: odom
base_frame_id: base_link
global_frame_id: map

# ===== Laser model =====
laser_min_range: 0.05
laser_max_range: 12.0
laser_max_beams: 360

laser_model_type: likelihood_field
laser_z_hit: 0.95
laser_z_short: 0.1
laser_z_max: 0.05
laser_z_rand: 0.05
laser_sigma_hit: 0.2

# ===== Motion model (HOLONOMIC) =====
odom_model_type: omni

odom_alpha1: 0.2
odom_alpha2: 0.2
odom_alpha3: 0.2
odom_alpha4: 0.2
odom_alpha5: 0.1

# ===== Particle filter =====
min_particles: 500
max_particles: 2000
kld_err: 0.05
kld_z: 0.99

# ===== Update thresholds =====
update_min_d: 0.05
update_min_a: 0.05

resample_interval: 1
transform_tolerance: 0.5

recovery_alpha_slow: 0.0
recovery_alpha_fast: 0.0
