obstacle_range: 2.5
raytrace_range: 3.0

footprint: [[0.25, 0.20], [0.25, -0.20], [-0.25, -0.20], [-0.25, 0.20]]
inflation_radius: 0.5

obstacle_layer:
  enabled: true
  observation_sources: scan
  scan:
    topic: scan
    sensor_frame: laser
    data_type: LaserScan
    marking: true
    clearing: true

inflation_layer:
  enabled: true
